options:
    bootstrap_url:
        type: string
        default: ''
        description: 'Bootstrap url edit with caution'
    oauth_enabled:
        type: boolean
        default: true
        description: 'Enable or disable the OAuth authentication(reinstall required)'
    telementary_enabled:
        type: boolean
        default: true
        description: 'Enable or disable the sending of anonymous telemetry to Mesosphere' 
